import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Modal from "@/components/modals/Modal";
import RegisterModal from "@/components/modals/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";


export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};
const font=Nunito({
  subsets:['latin'],
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={font.className}>
          {/* <Modal actionLabel="Submit" isOpen  title="hello" /> */}
          <ToasterProvider/>
          <RegisterModal/>
          <Navbar/>
        {children}
        
        </body>
    </html>
  );
}
