import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Modal from "@/components/modals/Modal";
import RegisterModal from "@/components/modals/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "@/components/modals/LoginModal";
import getCurrentUser from "./actions/getCurrentUser";
import RentModal from "@/components/modals/RentModal";


export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};
const font=Nunito({
  subsets:['latin'],
})
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser=await getCurrentUser()

  return (
    <html lang="en">
      <body  className={font.className}>
   
          <ToasterProvider/>
          <RegisterModal/>
          <LoginModal/>
          <RentModal/>
          <Navbar currentUser={currentUser} />
        {children}
        
        </body>
    </html>
  );
}
